# split into tissue specific samples
- [Make a set of data  table from scratch ](https://support.terra.bio/hc/en-us/articles/360047611871#h_01EJXZMM6GA3481YRRQBR65MY3)
- [Data Tables QuickStart Part 3: Understanding sets of data](https://support.terra.bio/hc/en-us/articles/360047611871)
- [adding data to a workspace with a template](https://support.terra.bio/hc/en-us/articles/360059242671). see "Sets of data - sample_set table"

In [1]:
import pandas as pd

# Load AnVIL_GTEx_V8_hg38_edu_ucsc_kim_lab  sample data table

In [2]:
rootDir = "../../data/AnVIL_GTEx_V8_hg38_edu_ucsc_kim_lab"
entityName = "sample"
sampleTSV = rootDir + "/" + entityName + ".tsv"
sampleDF = pd.read_csv(sampleTSV, delimiter='\t')
sampleDF.head()

,entity:sample_id,bam_file,bam_index,participant,tissue_id,tissue_site_detail
0,GTEX-1117F-0226-SM-5GZZ7,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,GTEX-1117F,Adipose_Subcutaneous,Adipose - Subcutaneous
1,GTEX-1117F-0426-SM-5EGHI,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,GTEX-1117F,Muscle_Skeletal,Muscle - Skeletal
2,GTEX-1117F-0526-SM-5EGHJ,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,GTEX-1117F,Artery_Tibial,Artery - Tibial
3,GTEX-1117F-0626-SM-5N9CS,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,GTEX-1117F,Artery_Coronary,Artery - Coronary
4,GTEX-1117F-0726-SM-5GIEN,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,gs://fc-secure-ff8156a3-ddf3-42e4-9211-0fd89da...,GTEX-1117F,Heart_Atrial_Appendage,Heart - Atrial Appendage

In [3]:
tissueTypes = pd.unique( sampleDF.loc[:, "tissue_id"] )
tissueTypes

array(['Adipose_Subcutaneous', 'Muscle_Skeletal', 'Artery_Tibial',
       'Artery_Coronary', 'Heart_Atrial_Appendage',
       'Adipose_Visceral_Omentum', 'Uterus', 'Vagina',
       'Breast_Mammary_Tissue', 'Skin_Not_Sun_Exposed_Suprapubic',
       'Minor_Salivary_Gland', 'Brain_Cortex', 'Adrenal_Gland', 'Thyroid',
       'Lung', 'Spleen', 'Pancreas', 'Esophagus_Muscularis',
       'Esophagus_Mucosa', 'Esophagus_Gastroesophageal_Junction',
       'Stomach', 'Colon_Sigmoid', 'Small_Intestine_Terminal_Ileum',
       'Colon_Transverse', 'Prostate', 'Testis', 'Nerve_Tibial',
       'Skin_Sun_Exposed_Lower_leg', 'Heart_Left_Ventricle',
       'Brain_Cerebellum', 'Cells_Cultured_fibroblasts', 'Whole_Blood',
       'Artery_Aorta', 'Cells_EBV-transformed_lymphocytes', 'Pituitary',
       'Brain_Frontal_Cortex_BA9', 'Brain_Caudate_basal_ganglia',
       'Brain_Nucleus_accumbens_basal_ganglia',
       'Brain_Putamen_basal_ganglia', 'Brain_Hypothalamus',
       'Brain_Spinal_cord_cervical_c-1', 'Brain_Hippocampus',
       'Brain_Anterior_cingulate_cortex_BA24', 'Ovary',
       'Brain_Cerebellar_Hemisphere', 'Liver', 'Brain_Substantia_nigra',
       'Kidney_Cortex', 'Brain_Amygdala', 'Cervix_Ectocervix',
       'Fallopian_Tube', 'Cervix_Endocervix', 'Bladder', 'Kidney_Medulla'],
      dtype=object)

# expected set format
- ID (first column) 
    The first column is the ID column, the unique name of the set. The format is '<span style="color:red">membership:</span>your-entity-name<span style="color:red">_set_id</span>'. The parts in red are required exactly as typed. The entity-name is whatever the entity you are grouping together. For the Data-QuickStart it will be specimens, but if your workflow processes samples, it could be samples. 


- Entity column
    The second column is the entity you're grouping into sets. The header must match the first column header of the table your workflow will take its single inputs from.

Given a sample.tsv file  our sample_set file is 
```
(base) $ cat sample_set_membership.tsv 
membership:sample_set_id	sample
set-d-4-panc	GTEX-11GSP-0426-SM-5A5KX
set-d-4-panc	GTEX-11I78-0626-SM-5A5LZ
set-d-4-panc	GTEX-11LCK-0226-SM-5A5M6
set-d-4-panc	GTEX-11NSD-0526-SM-5A5LT
```

In [4]:
# selectRows = sampleDF.loc[:, "tissue_id"] == tissueTypes[0]
#     tDF = sampleDF.loc[selectRows, :]

setDF = sampleDF.loc[ :, ['tissue_id',"entity:sample_id"] ].sort_values( by=['tissue_id'] )
setDF.head()

                 tissue_id          entity:sample_id
0     Adipose_Subcutaneous  GTEX-1117F-0226-SM-5GZZ7
6827  Adipose_Subcutaneous  GTEX-1B8KE-2526-SM-73KYQ
6798  Adipose_Subcutaneous  GTEX-1AYD5-2326-SM-73KXF
6784  Adipose_Subcutaneous  GTEX-1AYCT-2226-SM-7SB98
6762  Adipose_Subcutaneous  GTEX-1AX9K-2426-SM-73KZ4

In [5]:
setId = "membership:" +  entityName  + "_set_id"
terraColNames = [ setId , entityName ]
setDF.columns = terraColNames
setDF.head()

     membership:sample_set_id                    sample
0        Adipose_Subcutaneous  GTEX-1117F-0226-SM-5GZZ7
6827     Adipose_Subcutaneous  GTEX-1B8KE-2526-SM-73KYQ
6798     Adipose_Subcutaneous  GTEX-1AYD5-2326-SM-73KXF
6784     Adipose_Subcutaneous  GTEX-1AYCT-2226-SM-7SB98
6762     Adipose_Subcutaneous  GTEX-1AX9K-2426-SM-73KZ4

In [6]:
pancTissue = 'Pancreas'
pancRows = setDF.loc[:, setId] == pancTissue
pancSetDF = setDF.loc[ pancRows ]
print(pancSetDF.count())
pancSetDF.head()

membership:sample_set_id    328
sample                      328
dtype: int64

      membership:sample_set_id                    sample
12417                 Pancreas   GTEX-NPJ8-2126-SM-3MJGK
6838                  Pancreas  GTEX-1B8KZ-0926-SM-731D7
12743                 Pancreas   GTEX-P4PP-1026-SM-3NM9O
12763                 Pancreas   GTEX-P4PQ-1026-SM-3NMCN
12778                 Pancreas   GTEX-P4QS-1026-SM-3NMCW

In [7]:
n = 10
pancSet10DF = pancSetDF.sample(n).copy(deep=True)
pancSet10DF[setId] = pancTissue + "_" + str(n)
pancSet10DF

      membership:sample_set_id                    sample
8482               Pancreas_10  GTEX-1GZ4H-0626-SM-9OSXJ
6977               Pancreas_10  GTEX-1B933-1726-SM-731FC
10629              Pancreas_10  GTEX-1K9T9-1726-SM-CXZK1
13144              Pancreas_10   GTEX-QDVJ-1226-SM-48U1V
15622              Pancreas_10   GTEX-XV7Q-0926-SM-4BRVQ
16290              Pancreas_10   GTEX-ZAB5-0826-SM-5P9FU
1535               Pancreas_10  GTEX-12WSN-0826-SM-5GCOF
13073              Pancreas_10   GTEX-Q734-0426-SM-48TZX
8140               Pancreas_10  GTEX-1GL5R-0926-SM-9JGFO
6790               Pancreas_10  GTEX-1AYD5-0326-SM-7EWEO

In [8]:
 #pancSet10DF.loc[:, "sample"]
pancSet10DF["sample"].to_list()

['GTEX-1GZ4H-0626-SM-9OSXJ',
 'GTEX-1B933-1726-SM-731FC',
 'GTEX-1K9T9-1726-SM-CXZK1',
 'GTEX-QDVJ-1226-SM-48U1V',
 'GTEX-XV7Q-0926-SM-4BRVQ',
 'GTEX-ZAB5-0826-SM-5P9FU',
 'GTEX-12WSN-0826-SM-5GCOF',
 'GTEX-Q734-0426-SM-48TZX',
 'GTEX-1GL5R-0926-SM-9JGFO',
 'GTEX-1AYD5-0326-SM-7EWEO']

In [9]:
print( pancSet10DF["sample"] )
print()
selectRows = pancSetDF.loc[:, "sample"].isin( pancSet10DF["sample"] )
pancSetDF.loc[selectRows, :]

8482     GTEX-1GZ4H-0626-SM-9OSXJ
6977     GTEX-1B933-1726-SM-731FC
10629    GTEX-1K9T9-1726-SM-CXZK1
13144     GTEX-QDVJ-1226-SM-48U1V
15622     GTEX-XV7Q-0926-SM-4BRVQ
16290     GTEX-ZAB5-0826-SM-5P9FU
1535     GTEX-12WSN-0826-SM-5GCOF
13073     GTEX-Q734-0426-SM-48TZX
8140     GTEX-1GL5R-0926-SM-9JGFO
6790     GTEX-1AYD5-0326-SM-7EWEO
Name: sample, dtype: object

      membership:sample_set_id                    sample
1535                  Pancreas  GTEX-12WSN-0826-SM-5GCOF
6977                  Pancreas  GTEX-1B933-1726-SM-731FC
6790                  Pancreas  GTEX-1AYD5-0326-SM-7EWEO
16290                 Pancreas   GTEX-ZAB5-0826-SM-5P9FU
10629                 Pancreas  GTEX-1K9T9-1726-SM-CXZK1
13073                 Pancreas   GTEX-Q734-0426-SM-48TZX
13144                 Pancreas   GTEX-QDVJ-1226-SM-48U1V
8140                  Pancreas  GTEX-1GL5R-0926-SM-9JGFO
8482                  Pancreas  GTEX-1GZ4H-0626-SM-9OSXJ
15622                 Pancreas   GTEX-XV7Q-0926-SM-4BRVQ

In [10]:
assert 10 == sum( pancSetDF.loc[selectRows, "membership:sample_set_id"] == pancTissue )

## Save the the two data sets as a TSV file

In [11]:
finalDataSetDF = pd.concat( [pancSetDF, pancSet10DF] )
path = rootDir +  "/" +  entityName + "_set_membership.tsv" 
print(path)
finalDataSetDF.to_csv( path, sep='\t', index=False )

../../data/AnVIL_GTEx_V8_hg38_edu_ucsc_kim_lab/sample_set_membership.tsv

In [15]:
!head -n 3 $path
!tail -n 2 $path

membership:sample_set_id	sample
Pancreas	GTEX-NPJ8-2126-SM-3MJGK
Pancreas	GTEX-1B8KZ-0926-SM-731D7
Pancreas_10	GTEX-1GL5R-0926-SM-9JGFO
Pancreas_10	GTEX-1AYD5-0326-SM-7EWEO